# Generated by Django 5.0.7 on 2024-07-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inregistrare", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
