# Generated by Django 5.0.7 on 2024-07-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inregistrare", "0002_remove_profile_bio_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.CharField(max_length=255),
        ),
    ]
