# Generated by Django 5.0.7 on 2024-07-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inregistrare", "0003_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
