# Generated by Django 5.0.7 on 2024-07-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inregistrare", "0005_profile_email_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
