# Generated by Django 5.0.7 on 2024-07-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inregistrare", "0007_profile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile/user_images/"
            ),
        ),
    ]
