# Generated by Django 5.0.7 on 2024-07-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inregistrare", "0008_profile_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user_avatar",
        ),
    ]
