# Generated by Django 6.0 on 2026-03-17 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inregistrare", "0010_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="accepted_terms",
            field=models.BooleanField(default=False, verbose_name="Termeni acceptați"),
        ),
        migrations.AddField(
            model_name="profile",
            name="accepted_terms_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data acceptării termenilor"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="accepted_terms_version",
            field=models.CharField(
                blank=True,
                default="v1",
                max_length=20,
                verbose_name="Versiunea termenilor",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="age",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(6),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Vârstă",
            ),
        ),
    ]
