# Generated by Django 5.1.3 on 2024-11-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudy', '0004_reward_lesson_resources_test_userreward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='resources',
            field=models.TextField(blank=True, null=True),
        ),
    ]
