# Generated by Django 4.2 on 2025-09-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudy', '0006_alter_lesson_options_remove_lesson_resources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='practice_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='test',
            name='theory_summary',
            field=models.TextField(blank=True),
        ),
    ]
