# Generated by Django 4.2 on 2025-09-25 04:06

from django.db import migrations, models
import django.db.models.deletion
import estudy.models


class Migration(migrations.Migration):

    dependencies = [
        ('estudy', '0007_test_practice_prompt_test_theory_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='age_bracket',
            field=models.CharField(choices=[('8-10', '8-10 ani'), ('11-13', '11-13 ani'), ('14-16', '14-16 ani'), ('16+', '16+ ani')], default='11-13', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='theory_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='theory_takeaways',
            field=models.JSONField(blank=True, default=estudy.models.default_theory_takeaways),
        ),
        migrations.CreateModel(
            name='LessonPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True)),
                ('instructions', models.CharField(blank=True, max_length=200)),
                ('success_message', models.CharField(default='Super! Ai reușit să potrivești corect.', max_length=150)),
                ('data', models.JSONField(blank=True, default=estudy.models.default_practice_data)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practice', to='estudy.lesson')),
            ],
        ),
    ]
