# Generated by Django 4.2 on 2025-11-09 23:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import estudy.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("estudy", "0013_code_exercises"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("speed", "Speed"),
                            ("accuracy", "Accuracy"),
                            ("creativity", "Creativity"),
                            ("combo", "Combo"),
                        ],
                        default="speed",
                        max_length=20,
                    ),
                ),
                ("target_time_seconds", models.PositiveIntegerField(default=300)),
                (
                    "target_accuracy",
                    models.FloatField(
                        default=90.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("xp_reward", models.PositiveIntegerField(default=50)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "badge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lesson_challenges",
                        to="estudy.badge",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When the download expires"),
                ),
                ("cached_content", models.JSONField(default=dict)),
                ("cached_media_urls", models.JSONField(default=list)),
                ("file_size_mb", models.FloatField(default=0)),
            ],
            options={
                "ordering": ["-downloaded_at"],
            },
        ),
        migrations.CreateModel(
            name="LessonEasterEgg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger_condition",
                    models.CharField(
                        help_text="Condition to trigger the easter egg", max_length=100
                    ),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("badge", "Badge"),
                            ("xp", "XP"),
                            ("unlock", "Unlock"),
                        ],
                        default="xp",
                        max_length=20,
                    ),
                ),
                ("reward_value", models.PositiveIntegerField(default=0)),
                (
                    "message",
                    models.TextField(
                        help_text="Message shown when easter egg is found"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_quality",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "difficulty_appropriate",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "examples_helpful",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("what_worked", models.TextField(blank=True)),
                ("what_didnt_work", models.TextField(blank=True)),
                ("suggestions", models.TextField(blank=True)),
                ("would_recommend", models.BooleanField(default=True)),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(
                        default=0, help_text="Time to complete in minutes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LessonHint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        help_text="Section of the lesson (theory, practice, test)",
                        max_length=100,
                    ),
                ),
                ("hint_text", models.TextField()),
                (
                    "hint_level",
                    models.IntegerField(
                        default=1, help_text="1=easy, 2=medium, 3=full answer"
                    ),
                ),
                ("trigger_after_seconds", models.PositiveIntegerField(default=300)),
                ("show_after_attempts", models.PositiveIntegerField(default=2)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["lesson", "section", "hint_level"],
            },
        ),
        migrations.CreateModel(
            name="LessonModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("content", models.TextField()),
                (
                    "module_type",
                    models.CharField(
                        choices=[
                            ("concept", "Concept"),
                            ("example", "Example"),
                            ("practice", "Practice"),
                            ("quiz", "Mini-quiz"),
                        ],
                        default="concept",
                        max_length=20,
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=5)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["lesson", "order"],
            },
        ),
        migrations.CreateModel(
            name="LessonPersonalization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_hints", models.BooleanField(default=True)),
                ("show_extra_examples", models.BooleanField(default=False)),
                (
                    "content_difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("estimated_time_minutes", models.PositiveIntegerField(default=45)),
                ("actual_time_minutes", models.PositiveIntegerField(default=0)),
                (
                    "preferred_media",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("video", "Video"),
                            ("mixed", "Mixed"),
                        ],
                        default="mixed",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("content", models.TextField()),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("introduction", "Introduction"),
                            ("theory", "Theory"),
                            ("example", "Examples"),
                            ("practice", "Practice"),
                            ("summary", "Summary"),
                        ],
                        default="theory",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("requires_previous_complete", models.BooleanField(default=True)),
                ("unlock_after_seconds", models.PositiveIntegerField(default=0)),
                (
                    "comprehension_quiz",
                    models.JSONField(
                        default=list, help_text="Mini-questions to check understanding"
                    ),
                ),
            ],
            options={
                "ordering": ["lesson", "order"],
            },
        ),
        migrations.CreateModel(
            name="LessonStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_streak", models.PositiveIntegerField(default=0)),
                ("longest_streak", models.PositiveIntegerField(default=0)),
                ("last_lesson_date", models.DateField(blank=True, null=True)),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estudy.subject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_streaks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "subject")},
            },
        ),
        migrations.CreateModel(
            name="ModuleProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed", models.BooleanField(default=False)),
                ("understood", models.BooleanField(default=False)),
                ("time_spent_seconds", models.PositiveIntegerField(default=0)),
                (
                    "quiz_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="estudy.lessonmodule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
                "unique_together": {("user", "module")},
            },
        ),
        migrations.CreateModel(
            name="SectionProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed", models.BooleanField(default=False)),
                ("understood", models.BooleanField(default=False)),
                ("time_spent_seconds", models.PositiveIntegerField(default=0)),
                (
                    "quiz_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="estudy.lessonsection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
                "unique_together": {("user", "section")},
            },
        ),
        migrations.CreateModel(
            name="VideoProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watched_seconds", models.PositiveIntegerField(default=0)),
                (
                    "completion_percent",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("last_position", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-completed_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="challengeattempt",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="challengeattempt",
            name="challenge",
        ),
        migrations.RemoveField(
            model_name="challengeattempt",
            name="user",
        ),
        migrations.RemoveField(
            model_name="classassignment",
            name="classroom",
        ),
        migrations.RemoveField(
            model_name="classassignment",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="classassignment",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="classassignment",
            name="project",
        ),
        migrations.RemoveField(
            model_name="classroom",
            name="owner",
        ),
        migrations.AlterUniqueTogether(
            name="classroommembership",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="classroommembership",
            name="classroom",
        ),
        migrations.RemoveField(
            model_name="classroommembership",
            name="user",
        ),
        migrations.RemoveField(
            model_name="communityreply",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="communityreply",
            name="thread",
        ),
        migrations.RemoveField(
            model_name="communitythread",
            name="created_by",
        ),
        migrations.AlterUniqueTogether(
            name="learningpathlesson",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="learningpathlesson",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="learningpathlesson",
            name="path",
        ),
        migrations.AlterUniqueTogether(
            name="learningrecommendation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="learningrecommendation",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="learningrecommendation",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="parentchildlink",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="parentchildlink",
            name="child",
        ),
        migrations.RemoveField(
            model_name="parentchildlink",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="project",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="project",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="student",
        ),
        migrations.RemoveField(
            model_name="leaderboardsnapshot",
            name="classroom",
        ),
        migrations.AddField(
            model_name="lesson",
            name="audio_duration_seconds",
            field=models.PositiveIntegerField(
                default=0, help_text="Duration of the audio in seconds"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="audio_url",
            field=models.URLField(blank=True, help_text="URL of the audio file"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="slides_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of slides in the presentation"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="slides_url",
            field=models.URLField(
                blank=True, help_text="URL of the presentation/slides"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_duration_seconds",
            field=models.PositiveIntegerField(
                default=0, help_text="Duration of the video in seconds"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("youtube", "YouTube"),
                    ("vimeo", "Vimeo"),
                    ("self", "Self-hosted"),
                ],
                help_text="Platform where the video is hosted",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Thumbnail image for the video",
                null=True,
                upload_to="videos/thumbnails/",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL of the video (YouTube, Vimeo, or self-hosted)",
            ),
        ),
        migrations.AlterField(
            model_name="codeexercise",
            name="hints",
            field=models.JSONField(
                blank=True, default=estudy.models.default_empty_list
            ),
        ),
        migrations.AlterField(
            model_name="codeexercise",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="codeexercise",
            name="test_cases",
            field=models.JSONField(
                blank=True, default=estudy.models.default_empty_list
            ),
        ),
        migrations.AlterField(
            model_name="codesubmission",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="AssignmentSubmission",
        ),
        migrations.DeleteModel(
            name="ChallengeAttempt",
        ),
        migrations.DeleteModel(
            name="ClassAssignment",
        ),
        migrations.DeleteModel(
            name="Classroom",
        ),
        migrations.DeleteModel(
            name="ClassroomMembership",
        ),
        migrations.DeleteModel(
            name="CommunityReply",
        ),
        migrations.DeleteModel(
            name="CommunityThread",
        ),
        migrations.DeleteModel(
            name="DailyChallenge",
        ),
        migrations.DeleteModel(
            name="LearningPath",
        ),
        migrations.DeleteModel(
            name="LearningPathLesson",
        ),
        migrations.DeleteModel(
            name="LearningRecommendation",
        ),
        migrations.DeleteModel(
            name="ParentChildLink",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="ProjectSubmission",
        ),
        migrations.AddField(
            model_name="videoprogress",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_progress",
                to="estudy.lesson",
            ),
        ),
        migrations.AddField(
            model_name="videoprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lessonsection",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="estudy.lesson",
            ),
        ),
        migrations.AddField(
            model_name="lessonpersonalization",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personalizations",
                to="estudy.lesson",
            ),
        ),
        migrations.AddField(
            model_name="lessonpersonalization",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_personalizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lessonmodule",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="estudy.lesson",
            ),
        ),
        migrations.AddField(
            model_name="lessonmodule",
            name="requires_modules",
            field=models.ManyToManyField(blank=True, to="estudy.lessonmodule"),
        ),
        migrations.AddField(
            model_name="lessonhint",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hints",
                to="estudy.lesson",
            ),
        ),
        migrations.AddField(
            model_name="lessonfeedback",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="estudy.lesson",
            ),
        ),
        migrations.AddField(
            model_name="lessonfeedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_feedbacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lessoneasteregg",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="easter_eggs",
                to="estudy.lesson",
            ),
        ),
        migrations.AddField(
            model_name="lessondownload",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="downloads",
                to="estudy.lesson",
            ),
        ),
        migrations.AddField(
            model_name="lessondownload",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_downloads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lessonchallenge",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenges",
                to="estudy.lesson",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="videoprogress",
            unique_together={("user", "lesson")},
        ),
        migrations.AlterUniqueTogether(
            name="lessonpersonalization",
            unique_together={("user", "lesson")},
        ),
        migrations.AlterUniqueTogether(
            name="lessonfeedback",
            unique_together={("lesson", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="lessondownload",
            unique_together={("user", "lesson")},
        ),
    ]
