# Generated by Django 4.2 on 2025-11-09 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estudy", "0014_lessonchallenge_lessondownload_lessoneasteregg_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("theme", models.CharField(default="rainbow", max_length=40)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("audience", models.CharField(default="general", max_length=60)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("time_taken_ms", models.PositiveIntegerField(default=0)),
                ("awarded_points", models.PositiveIntegerField(default=0)),
                ("earned_bonus", models.BooleanField(default=False)),
                ("feedback", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="LearningPathLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_items",
                        to="estudy.lesson",
                    ),
                ),
                (
                    "path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="estudy.learningpath",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "unique_together": {("path", "lesson")},
            },
        ),
    ]
