# Generated by Django 4.2 on 2025-11-09 23:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("estudy", "0016_learningrecommendation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="audio_duration_seconds",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="audio_url",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="slides_count",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="slides_url",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="video_duration_seconds",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="video_platform",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="video_thumbnail",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="video_url",
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("interactive", "Interactive"),
                    ("project", "Project"),
                    ("quiz", "Quiz"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LessonMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="URL of the video (YouTube, Vimeo, or self-hosted)",
                    ),
                ),
                (
                    "video_platform",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("youtube", "YouTube"),
                            ("vimeo", "Vimeo"),
                            ("self", "Self-hosted"),
                        ],
                        help_text="Platform where the video is hosted",
                        max_length=20,
                    ),
                ),
                (
                    "video_duration_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Duration of the video in seconds"
                    ),
                ),
                (
                    "video_thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail image for the video",
                        null=True,
                        upload_to="videos/thumbnails/",
                    ),
                ),
                (
                    "audio_url",
                    models.URLField(blank=True, help_text="URL of the audio file"),
                ),
                (
                    "audio_duration_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Duration of the audio in seconds"
                    ),
                ),
                (
                    "slides_url",
                    models.URLField(
                        blank=True, help_text="URL of the presentation/slides"
                    ),
                ),
                (
                    "slides_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of slides in the presentation"
                    ),
                ),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="estudy.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson Media",
                "verbose_name_plural": "Lesson Media",
            },
        ),
        migrations.CreateModel(
            name="LessonComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("is_approved", models.BooleanField(default=True)),
                ("is_hidden", models.BooleanField(default=False)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("replies_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="estudy.lesson",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="estudy.lessoncomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LessonAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("views", models.PositiveIntegerField(default=0)),
                ("unique_views", models.PositiveIntegerField(default=0)),
                ("completions", models.PositiveIntegerField(default=0)),
                (
                    "avg_time_spent",
                    models.PositiveIntegerField(
                        default=0, help_text="Average time spent in seconds"
                    ),
                ),
                (
                    "median_time_spent",
                    models.PositiveIntegerField(
                        default=0, help_text="Median time spent in seconds"
                    ),
                ),
                (
                    "avg_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "completion_rate",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "drop_off_points",
                    models.JSONField(
                        default=dict,
                        help_text="Where students drop off (section -> count)",
                    ),
                ),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("ratings_count", models.PositiveIntegerField(default=0)),
                (
                    "avg_rating",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("error_count", models.PositiveIntegerField(default=0)),
                (
                    "load_time_avg",
                    models.PositiveIntegerField(
                        default=0, help_text="Average load time in ms"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="estudy.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="estudy.lessoncomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("review", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="estudy.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("lesson", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="lessoncomment",
            index=models.Index(
                fields=["lesson", "created_at"], name="lesson_comments_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessoncomment",
            index=models.Index(
                fields=["parent", "created_at"], name="comment_replies_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonanalytics",
            index=models.Index(fields=["lesson", "date"], name="lesson_analytics_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="lessonanalytics",
            unique_together={("lesson", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="commentlike",
            unique_together={("user", "comment")},
        ),
    ]
