# Generated by Django 5.0.7 on 2025-11-10 00:12

import django.db.models.deletion
from django.db import migrations, models

import estudy.models


class Migration(migrations.Migration):
    dependencies = [
        ("estudy", "0018_placeholder_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="collaboration_mode",
            field=models.CharField(
                choices=[
                    ("solo", "Individual"),
                    ("pairs", "In pairs"),
                    ("small_group", "Small group"),
                    ("whole_class", "Whole class"),
                ],
                default="solo",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="content_tracks",
            field=models.JSONField(
                blank=True, default=estudy.models.default_empty_list
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="discussion_prompts",
            field=models.JSONField(
                blank=True, default=estudy.models.default_empty_list
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="home_extension",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="story_anchor",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name="lesson",
            name="warmup_prompt",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="LessonMediaSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("start_seconds", models.PositiveIntegerField(default=0)),
                ("end_seconds", models.PositiveIntegerField(default=0)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="estudy.lessonmedia",
                    ),
                ),
            ],
            options={
                "ordering": ("media", "order", "id"),
            },
        ),
        migrations.CreateModel(
            name="LessonObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("focus_area", models.CharField(blank=True, max_length=120)),
                ("success_criteria", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectives",
                        to="estudy.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ("lesson", "order", "id"),
            },
        ),
        migrations.CreateModel(
            name="LessonReflectionPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.CharField(max_length=255)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("text", "Open response"),
                            ("scale", "Rating scale"),
                            ("draw", "Creative"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "scale_labels",
                    models.JSONField(
                        blank=True, default=estudy.models.default_empty_list
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reflection_prompts",
                        to="estudy.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ("lesson", "order", "id"),
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="lessons", to="estudy.skill"
            ),
        ),
    ]
