# Generated by Django 4.2 on 2025-11-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estudy", "0020_auto_populate_lesson_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="collaboration_mode",
            field=models.CharField(
                choices=[
                    ("solo", "Individual"),
                    ("pairs", "În perechi"),
                    ("small_group", "În echipe mici"),
                    ("whole_class", "Împreună cu clasa"),
                ],
                default="solo",
                max_length=30,
            ),
        ),
    ]
