# Generated by Django 4.2 on 2025-11-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estudy", "0021_alter_lesson_collaboration_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonmedia",
            name="audio_duration_seconds",
            field=models.PositiveIntegerField(
                default=0, help_text="Durata audio în secunde"
            ),
        ),
        migrations.AlterField(
            model_name="lessonmedia",
            name="audio_url",
            field=models.URLField(blank=True, help_text="URL-ul fișierului audio"),
        ),
        migrations.AlterField(
            model_name="lessonmedia",
            name="slides_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Numărul de slide-uri din prezentare"
            ),
        ),
        migrations.AlterField(
            model_name="lessonmedia",
            name="slides_url",
            field=models.URLField(blank=True, help_text="URL-ul prezentării/slidelor"),
        ),
        migrations.AlterField(
            model_name="lessonmedia",
            name="video_duration_seconds",
            field=models.PositiveIntegerField(
                default=0, help_text="Durata videoclipului în secunde"
            ),
        ),
        migrations.AlterField(
            model_name="lessonmedia",
            name="video_platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("youtube", "YouTube"),
                    ("vimeo", "Vimeo"),
                    ("self", "Self-hosted"),
                ],
                help_text="Platforma pe care este găzduit videoclipul",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lessonmedia",
            name="video_thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Imagine reprezentativă pentru videoclip",
                null=True,
                upload_to="videos/thumbnails/",
            ),
        ),
        migrations.AlterField(
            model_name="lessonmedia",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL-ul videoclipului (YouTube, Vimeo sau găzduit intern)",
            ),
        ),
    ]
