# Generated by Django 5.0.7 on 2026-01-03 01:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("estudy", "0031_fix_project_created_at"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="eventlog",
            new_name="estudy_even_event_t_548230_idx",
            old_name="event_type_created_idx",
        ),
        migrations.RenameIndex(
            model_name="eventlog",
            new_name="estudy_even_user_id_186bb8_idx",
            old_name="event_user_created_idx",
        ),
        migrations.RenameIndex(
            model_name="offlineprogressqueue",
            new_name="estudy_offl_user_id_b0ccb7_idx",
            old_name="offline_user_synced_idx",
        ),
        migrations.RenameIndex(
            model_name="offlineprogressqueue",
            new_name="estudy_offl_lesson__939cf2_idx",
            old_name="offline_lesson_synced_idx",
        ),
    ]
