# Generated by Django 6.0 on 2026-01-08 04:46

from django.db import migrations, models

import estudy.models


class Migration(migrations.Migration):
    dependencies = [
        ("estudy", "0036_audit_trail_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_trusted_contributor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reputation_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="aiusagecost",
            name="details",
            field=models.JSONField(
                blank=True, default=estudy.models.default_empty_dict
            ),
        ),
        migrations.AlterField(
            model_name="audittrailentry",
            name="metadata",
            field=models.JSONField(
                blank=True, default=estudy.models.default_empty_dict
            ),
        ),
    ]
