# Generated by Django 6.0 on 2026-01-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estudy", "0037_userprofile_is_trusted_contributor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("lesson_view", "Lesson view"),
                    ("test_start", "Test start"),
                    ("test_submit", "Test submit"),
                    ("achievement_awarded", "Achievement awarded"),
                    ("reputation_change", "Reputation change"),
                ],
                max_length=50,
            ),
        ),
    ]
