# Generated by Django 6.0 on 2026-01-09 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estudy", "0039_add_xp_decay_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("lesson_view", "Lesson view"),
                    ("test_start", "Test start"),
                    ("test_submit", "Test submit"),
                    ("achievement_awarded", "Achievement awarded"),
                    ("reputation_change", "Reputation change"),
                    ("xp_decay", "XP decay"),
                    ("community_curation", "Community curation"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="CommunityCuratedAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("curated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "curated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="curated_answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reply",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curation",
                        to="estudy.communityreply",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curated_answers",
                        to="estudy.communitythread",
                    ),
                ),
            ],
            options={
                "ordering": ("-curated_at",),
                "indexes": [
                    models.Index(
                        fields=["thread", "curated_at"], name="community_curated_idx"
                    )
                ],
            },
        ),
    ]
