# Generated by Django 6.0 on 2026-01-09 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estudy", "0040_community_curation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CosmeticPerk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("frame", "Avatar frame"),
                            ("aura", "Avatar aura"),
                            ("background", "Profile background"),
                        ],
                        default="frame",
                        max_length=30,
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                        ],
                        default="common",
                        max_length=20,
                    ),
                ),
                ("accent_color", models.CharField(blank=True, max_length=20)),
                ("unlock_min_level", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("category", "title"),
            },
        ),
        migrations.AlterField(
            model_name="eventlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("lesson_view", "Lesson view"),
                    ("test_start", "Test start"),
                    ("test_submit", "Test submit"),
                    ("achievement_awarded", "Achievement awarded"),
                    ("reputation_change", "Reputation change"),
                    ("xp_decay", "XP decay"),
                    ("community_curation", "Community curation"),
                    ("cosmetic_unlock", "Cosmetic unlock"),
                    ("cosmetic_equip", "Cosmetic equip"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="UserCosmeticPerk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=60)),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                ("is_equipped", models.BooleanField(default=False)),
                ("equipped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "perk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocks",
                        to="estudy.cosmeticperk",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cosmetic_perks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_equipped"],
                        name="cosmetic_user_equipped_idx",
                    )
                ],
                "unique_together": {("user", "perk")},
            },
        ),
    ]
