# Generated by Django 6.0 on 2026-01-09 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estudy", "0041_cosmetic_perks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("lesson_view", "Lesson view"),
                    ("test_start", "Test start"),
                    ("test_submit", "Test submit"),
                    ("achievement_awarded", "Achievement awarded"),
                    ("reputation_change", "Reputation change"),
                    ("xp_decay", "XP decay"),
                    ("community_curation", "Community curation"),
                    ("cosmetic_unlock", "Cosmetic unlock"),
                    ("cosmetic_equip", "Cosmetic equip"),
                    ("streak_freeze_grant", "Streak freeze grant"),
                    ("streak_freeze_use", "Streak freeze use"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="StreakFreezeBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available_tokens", models.PositiveIntegerField(default=0)),
                ("used_tokens", models.PositiveIntegerField(default=0)),
                ("last_awarded_streak", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak_freeze_balance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
    ]
