# Generated by Django 6.0 on 2026-01-09 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estudy", "0042_streak_freeze_tokens"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("theme", models.CharField(blank=True, max_length=40)),
                ("points_goal", models.PositiveIntegerField(default=100)),
                ("reward_xp", models.PositiveIntegerField(default=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-start_date",),
            },
        ),
        migrations.AlterField(
            model_name="eventlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("lesson_view", "Lesson view"),
                    ("test_start", "Test start"),
                    ("test_submit", "Test submit"),
                    ("achievement_awarded", "Achievement awarded"),
                    ("reputation_change", "Reputation change"),
                    ("xp_decay", "XP decay"),
                    ("community_curation", "Community curation"),
                    ("cosmetic_unlock", "Cosmetic unlock"),
                    ("cosmetic_equip", "Cosmetic equip"),
                    ("streak_freeze_grant", "Streak freeze grant"),
                    ("streak_freeze_use", "Streak freeze use"),
                    ("seasonal_progress", "Seasonal progress"),
                    ("seasonal_completed", "Seasonal completed"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="UserSeasonalProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_entries",
                        to="estudy.seasonalevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasonal_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "event"], name="seasonal_progress_user_event"
                    )
                ],
                "unique_together": {("user", "event")},
            },
        ),
    ]
