# Generated by Django 6.0 on 2026-01-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estudy", "0043_seasonal_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("lesson_view", "Lesson view"),
                    ("test_start", "Test start"),
                    ("test_submit", "Test submit"),
                    ("achievement_awarded", "Achievement awarded"),
                    ("reputation_change", "Reputation change"),
                    ("xp_decay", "XP decay"),
                    ("community_curation", "Community curation"),
                    ("cosmetic_unlock", "Cosmetic unlock"),
                    ("cosmetic_equip", "Cosmetic equip"),
                    ("streak_freeze_grant", "Streak freeze grant"),
                    ("streak_freeze_use", "Streak freeze use"),
                    ("seasonal_progress", "Seasonal progress"),
                    ("seasonal_completed", "Seasonal completed"),
                    ("offline_progress_sync", "Offline progress sync"),
                    ("offline_progress_conflict", "Offline progress conflict"),
                ],
                max_length=50,
            ),
        ),
    ]
