# Generated by Django 6.0 on 2026-02-25 03:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import estudy.models


class Migration(migrations.Migration):
    dependencies = [
        ("estudy", "0044_offline_progress_conflict_policy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RobotLabSkillProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequencing_score",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "loop_score",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "condition_score",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "function_score",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "debugging_score",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="robot_lab_skill_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="RobotLabAttemptLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_id", models.CharField(max_length=40)),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                ("error_type", models.CharField(default="logic", max_length=20)),
                ("primary_error", models.CharField(blank=True, max_length=80)),
                ("typical_error", models.CharField(default="unknown", max_length=80)),
                ("solved", models.BooleanField(default=False)),
                ("hints_used", models.PositiveIntegerField(default=0)),
                ("requested_solution", models.BooleanField(default=False)),
                (
                    "concept_focus",
                    models.CharField(
                        choices=[
                            ("sequencing", "Sequencing"),
                            ("condition", "Condition"),
                            ("loop", "Loop"),
                            ("function", "Function"),
                            ("debugging", "Debugging"),
                        ],
                        default="debugging",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=estudy.models.default_empty_dict
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="robot_lab_attempt_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="est_rl_att_u_created_idx",
                    ),
                    models.Index(
                        fields=["level_id", "created_at"],
                        name="est_rl_att_l_created_idx",
                    ),
                ],
            },
        ),
    ]
