# Generated by Django 6.0 on 2026-02-25 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import estudy.models


class Migration(migrations.Migration):
    dependencies = [
        ("estudy", "0045_robotlabskillprofile_robotlabattemptlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RobotLabLevelProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_id", models.CharField(max_length=40)),
                ("unlocked", models.BooleanField(default=False)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("best_steps", models.PositiveIntegerField(blank=True, null=True)),
                ("attempts_count", models.PositiveIntegerField(default=0)),
                ("xp_awarded_total", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="robot_lab_level_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("level_id",),
                "indexes": [
                    models.Index(
                        fields=["user", "updated_at"], name="est_rl_prog_u_updated_idx"
                    ),
                    models.Index(
                        fields=["level_id", "completed"], name="est_rl_prog_l_done_idx"
                    ),
                ],
                "unique_together": {("user", "level_id")},
            },
        ),
        migrations.CreateModel(
            name="RobotLabRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_id", models.CharField(max_length=40)),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                ("code", models.TextField()),
                ("error_type", models.CharField(default="logic", max_length=20)),
                ("primary_error", models.CharField(blank=True, max_length=80)),
                (
                    "execution_trace",
                    models.JSONField(
                        blank=True, default=estudy.models.default_empty_list
                    ),
                ),
                (
                    "final_state",
                    models.JSONField(
                        blank=True, default=estudy.models.default_empty_dict
                    ),
                ),
                (
                    "level_snapshot",
                    models.JSONField(
                        blank=True, default=estudy.models.default_empty_dict
                    ),
                ),
                ("steps_used", models.PositiveIntegerField(default=0)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("solved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="robot_lab_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"], name="est_rl_run_u_created_idx"
                    ),
                    models.Index(
                        fields=["level_id", "created_at"],
                        name="est_rl_run_l_created_idx",
                    ),
                ],
            },
        ),
    ]
