# Generated by Django 5.0.7 on 2026-04-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estudy", "0048_merge_duplicate_coding_quest_subjects"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="current_streak",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="longest_streak",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
