# Generated by Django 5.0.7 on 2026-04-06 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import estudy.models


class Migration(migrations.Migration):
    dependencies = [
        ("estudy", "0049_userprofile_current_streak_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dailychallenge",
            name="challenge_type",
            field=models.CharField(
                choices=[
                    ("complete", "Complete lesson"),
                    ("speed", "Speed run"),
                    ("quiz", "Quiz perfect score"),
                ],
                default="complete",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dailychallenge",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_challenges",
                to="estudy.lesson",
            ),
        ),
        migrations.AddField(
            model_name="dailychallenge",
            name="xp_bonus",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="subject",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="CoopSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                (
                    "session_code",
                    models.CharField(
                        default=estudy.models._generate_session_code,
                        max_length=6,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="joined_coop_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_coop_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coop_sessions",
                        to="estudy.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
