# Generated by Django 5.0.7 on 2026-04-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estudy", "0051_populate_subject_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=120, unique=True),
        ),
    ]
