# Generated by Django 5.0.7 on 2026-04-08 03:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estudy", "0052_make_subject_slug_non_nullable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RobotLabSkin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "unlock_condition",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("svg_file", models.CharField(blank=True, default="", max_length=100)),
                ("ordering", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("ordering", "key"),
            },
        ),
        migrations.AddField(
            model_name="robotlablevelprogress",
            name="stars_earned",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.CreateModel(
            name="UserRobotLabSkin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "skin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_skins",
                        to="estudy.robotlabskin",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="robot_lab_skins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("skin__ordering",),
                "unique_together": {("user", "skin")},
            },
        ),
    ]
