# Generated by Django 6.0 on 2026-03-24 15:27

from django.db import migrations


def merge_duplicate_coding_quest_subjects(apps, schema_editor):
    Subject = apps.get_model("estudy", "Subject")
    Lesson = apps.get_model("estudy", "Lesson")
    Course = apps.get_model("estudy", "Course")

    subjects = list(Subject.objects.filter(name="Coding Quest").order_by("id"))
    if len(subjects) <= 1:
        return

    canonical = subjects[0]
    duplicate_ids = [subject.id for subject in subjects[1:]]

    Lesson.objects.filter(subject_id__in=duplicate_ids).update(subject_id=canonical.id)
    Course.objects.filter(subject_id__in=duplicate_ids).update(subject_id=canonical.id)
    Subject.objects.filter(id__in=duplicate_ids).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("estudy", "0059_curate_python_lessons"),
    ]

    operations = [
        migrations.RunPython(
            merge_duplicate_coding_quest_subjects, migrations.RunPython.noop
        ),
    ]
